//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGE_ANIMA_GAME_TOOLS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\GAINAX\\IRONMAIDEN2")]
        public string main_folder {
            get {
                return ((string)(this["main_folder"]));
            }
            set {
                this["main_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\GAINAX\\IRONMAIDEN2\\exe\\00test03-latin.exe.lnk")]
        public string run_game_exe {
            get {
                return ((string)(this["run_game_exe"]));
            }
            set {
                this["run_game_exe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\GAINAX\\IRONMAIDEN2\\goslb5un1.exe.lnk")]
        public string goslb5un1 {
            get {
                return ((string)(this["goslb5un1"]));
            }
            set {
                this["goslb5un1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\GAINAX\\IRONMAIDEN2\\goslb5pk1.exe.lnk")]
        public string goslb5pk1 {
            get {
                return ((string)(this["goslb5pk1"]));
            }
            set {
                this["goslb5pk1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\GAINAX\\IRONMAIDEN2\\gosbp3un1.exe.lnk")]
        public string gosbp3un1 {
            get {
                return ((string)(this["gosbp3un1"]));
            }
            set {
                this["gosbp3un1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\GAINAX\\IRONMAIDEN2\\gosbp3pk1.exe.lnk")]
        public string gosbp3pk1 {
            get {
                return ((string)(this["gosbp3pk1"]));
            }
            set {
                this["gosbp3pk1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\GAINAX\\IRONMAIDEN2\\gostx31.exe.lnk")]
        public string gostx31 {
            get {
                return ((string)(this["gostx31"]));
            }
            set {
                this["gostx31"] = value;
            }
        }
    }
}
